### ISSUE TITLE
Brew formula for using on a Mac

### ISSUE THREAD

**Issue by cipri-tom** [dtrx-py/dtrx#20]
Hi !

Many thanks for the port ! I almost went away from `dtrx`, considering it abandonware, but thanks to you it still lives ! 👏 

Would you consider also hosting a small formula that would allow mac users to install it using `brew` ?
It could be as simple as this (old) one: https://github.com/xhochy/homebrew/blob/master/Library/Formula/dtrx.rb

Many thanks, already, for the great work !

**Comment by noahp** [comment]
Oh wow, thank you! I'll look into adding a brew formula, thanks for the suggestion!

**Comment by noahp** [comment]
Just leaving some notes for myself:
- dtrx formula was removed here due to dep on unrar: https://github.com/Homebrew/homebrew-core/pull/66609/commits/0a94a41668d224ac51393b1c97d73ad635daf91a
   can probably copy that and update it

- they also link to here: https://docs.brew.sh/Acceptable-Formulae so double check that before pr'ing

Interestingly, https://brettcsmith.org/2007/dtrx/ now redirects to this github repo!

**Comment by cipri-tom** [comment]
Hi Noah ! 

Just a small nudge that this would still be a great thing to have ^^ (found myself needing it again).
I'd consider making it, but it's best if you're the author, in case there are updates later on

**Comment by noahp** [comment]
Ok, looks like the brew formula has been merged!
